spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092
    admin:
      auto-create: true
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
